import = ["/home/manuel/.config/alacritty/themes/material-ocean.toml"]


[font]
size = 9.5

[font.bold]
family = "Caskaydia Cove Nerd Font Propo"
style = "Bold"

[font.bold_italic]
family = "Caskaydia Cove Nerd Font Propo"
style = "Bold Italic"

[font.italic]
family = "Caskaydia Cove Nerd Font Propo"
style = "Italic"

[font.normal]
family = "Caskaydia Cove Nerd Font Propo"
style = "Normal"

[window]
title = "Alacritty"
opacity = 0.90

[window.dimensions]
columns = 110
lines = 25

[window.padding]
x = 5
y = 3

